### ISSUE TITLE
boolean bugs

### ISSUE THREAD

**Issue by xyjigsaw** [kerighan/eldar#10]
'''
from eldar import Query

docs = ["the USA chaLLenges China",
        "Japan Likes uK",
        "cJapanese do not like china",
        "CHINA",
        "MM SJTU"]
query = Query('USA AND CHINA OR SJTU')
print(query.filter(docs))
'''

Hi there,
I want to get "the USA chaLLenges China" and "MM SJTU" but the result only shows the first one.

**Comment by kerighan** [comment]
These are not bugs, your query is malformed.
Boolean operations are binary operations, so you must specify parentheses when using AND and OR (as no priority has been defined for operations). I also recommend adding quotes to avoid confusion.
This works:
query = Query('("USA" AND "CHINA") OR "SJTU"')
