### ISSUE TITLE
not in chinese

### ISSUE THREAD

**Issue by lcp580** [kerighan/eldar#11]
from eldar import Query
documents = "是故内圣外王之道，暗而不明，郁而不发，天下之人各为其所欲焉以自为方。"
eldar = Query("不明")
print(eldar.filter(documents))
[]

====
err:not find chinese sentence
[]

**Comment by kerighan** [comment]
two problems in your request:
- when using the filter method, documents should be a list of strings
- use match_word=False to avoid having to match the whole token sequence
This works:
```
documents = ["是故内圣外王之道，暗而不明，郁而不发，天下之人各为其所欲焉以自为方。"]
eldar = Query("不明", match_word=False)
eldar.filter(documents)
```

**Comment by lcp580** [comment]
thank you very mach
