### ISSUE TITLE
AttributeError: 'float' object has no attribute 'lower'

### ISSUE THREAD

**Issue by MonikaBarget** [kerighan/eldar#14]
I was running a query on several data frames, and while worked OK, others raised this error:

```
21     def preprocess(self, doc):
     22         if self.ignore_case:
---> 23             doc = doc.lower()
     24         if self.ignore_accent:
     25             doc = unidecode(doc)

AttributeError: 'float' object has no attribute 'lower'
```
The data frames that caused this problem come from an EXCEL cell with text but "." in abbreviations such as "st." for "saint".

Will I need to strip punctuation first or is there a way to "convert" float to string within your eldar function?

**Comment by kerighan** [comment]
It might be because there are floats or nan values in your input data. Try applying str() on your texts first

**Comment by MonikaBarget** [comment]
Thanks, it is, indeed, a problem of empty cells. I have now tried two things:

1) `df` = pd.read_excel(file, sheet_name='FactoidList', axis=1, ignore_index=False, sort=False, dtype=str)
2) `df = df.where((pd.notnull(df)), None)` # replace empty fields for None

Neither of them does the trick, I am afraid. 

I will also test `dropna(inplace = True)`.

If I was only running eldar on one column at a time, I would easily exclude empty cells, but I want to integrate eldar into a numpy condition list to check several columns per row.

**Comment by MonikaBarget** [comment]
Nope, that did not fix it either. I wonder what happens if I use exception handling to by-pass the problem.

**Comment by kerighan** [comment]
Concerning your different comments:
AttributeError: 'float' object has no attribute 'lower'
This error is quite clear, you're not inputting string data to eldar. So you first have to clean your data and make sure that every item of your list/serie is a string.
