### ISSUE TITLE
local variable 'right_part' referenced before assignment

### ISSUE THREAD

**Issue by ecsquare** [kerighan/eldar#18]
Traceback:
  File "C:\Users\guest\eldar\query.py", line 19, in __init__
    self.query = parse_query(query, ignore_case, ignore_accent)
  File "C:\Users\emrec\PycharmProjects\nested_keyword_match\eldar\query.py", line 90, in parse_query
    parse_query(right_part, ignore_case, ignore_accent)
UnboundLocalError: local variable 'right_part' referenced before assignment

A priori verification of the query is required + removal of extra space (if there are space decomposing the query does not work expectedly)

**Comment by kerighan** [comment]
could you provide an example with this error please

**Comment by ecsquare** [comment]
> could you provide an example with this error please

**Comment by ecsquare** [comment]
> could you provide an example of this error, please

It happens when the user passes an unbalanced query or a query that contains white space
Example: "cat      AND dog" || "(cat OR dog" it would be a nice addition if an evaluation method is added before the search
