### ISSUE TITLE
Use install_requires in setup.py

### ISSUE THREAD

**Issue by impredicative** [kerighan/eldar#2]
It is standard practice to specify [`install_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#install-requires) in `setup.py` as an argument to `setup()` in order to document requirements. It can perhaps be specified as below:

```python
    install_requires = ["cython", "unidecode"],
```

Following this, `pip install eldar` should install both requirements automatically, saving me from having to manually install them.

**Comment by kerighan** [comment]
Thanks for your input.
In the new version, Cython support has been discontinued due to negligible performance gain.
```python
install_requires = ["unidecode>=1.1.1"]
```
has been added.
