### ISSUE TITLE
Option to not store entire document contents in index

### ISSUE THREAD

**Issue by distbit0** [kerighan/eldar#21]
It seems very space in efficient to store the entire document string in the index file for each indexed documents, rather than just the index dictionary.

Given I am working with a few Gb of text documents, it would be extremely useful to have eldar only store the necessary index data in the index file, rather than also the contents of the documents. 

Could you please an add an option to just store the document id instead of the document contents in the index? 

many thx

**Comment by distbit0** [comment]
What would be even better is if we could specify a custom "id" for each article. E.g. For my application it would make sense to make said key the file path to the article.

**Comment by kerighan** [comment]
I totally agree with the custom id idea.
The issue with indexing is that you are required to store the entire documents (not as complete strings but as a collection of tokens), or else you lose the ability to query phrases such as "new york city". A solution to this would be to store ngrams (bigrams, trigrams), but I doubt it will reduce the memory footprint much. Given that disk size is not expensive, I'd rather have large indexes than indexes that can only query isolated words.

**Comment by distbit0** [comment]
That makes sense. Thank you for the explanation. But yeah custom ids would be very useful as well :)
