### ISSUE TITLE
Bug with single "NOT" in query

### ISSUE THREAD

**Issue by khalo-sa** [kerighan/eldar#7]
Hi, and thank you for this library!
I think I discovered a bug with version 0.0.5 .

The following piece works as I would expect:
```python
from eldar import Query
eldar = Query('" " AND NOT "blacklisted"', match_word=False)
eldar("only contains whitelisted terms")
>>> True
```

For this however, I would expect it to return True as well, but it doesn't.
```python
from eldar import Query
eldar = Query('NOT "blacklisted"', match_word=False)
eldar("only contains whitelisted terms")
>>> False
```

**Comment by kerighan** [comment]
Hi,
Thanks for the bug report and sorry for the delay.
It's fixed now with 0.0.6.
